### ISSUE TITLE
Update copy in confirmation email for new accounts

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#199]
Title:  Confirmation of MSF ReMIT account

Body of text:

Welcome to ReMIT [INSERT EMAIL]!

You can confirm your account email through the link below:

[CONFIRM MY ACCOUNT LINK]

What is ReMIT?
------------------------
The Research Management and Impact Tool (ReMIT) is an open access research management system for all studies conducted by Médecins Sans Frontières Operational Centre Amsterdam (MSF-OCA). 

Why am I receiving this email?
---------------------------
You are receiving this email because you either registered to use ReMIT or because you are the PI for a study conducted by MSF-OCA and that study is now visible
 
Any questions?
--------------------------
Please reply to this email if you have any questions

**Comment by stevenday** [comment]
This is now done and live

**Comment by kimmwest** [comment]
@stevenday  - this looks great, although assume the parts in square brackets have been replaced with links.

The only amendment I have is the addition of 'in ReMIT' marked in bold below

Why am I receiving this email?

You are receiving this email because you either registered to use ReMIT or because you are the PI for a study conducted by MSF-OCA and that study is now visible **in ReMIT**

Thanks a million

**Comment by stevenday** [comment]
@kimmwest - I've added that in now.
