### ISSUE TITLE
Review study progress bar, timeline and "most recent action" card

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#57]
We've now completed the progress bar, timeline, and the "most recent action" card that display on the study page:

![screen shot 2016-01-27 at 17 26 21](https://cloud.githubusercontent.com/assets/663700/12621974/200b4e5a-c51b-11e5-9c1c-614a79ec5e14.png)

![screen shot 2016-01-27 at 17 19 55](https://cloud.githubusercontent.com/assets/663700/12621806/35b9e154-c51a-11e5-912f-420c3fd58388.png)

![screen shot 2016-01-27 at 17 19 49](https://cloud.githubusercontent.com/assets/663700/12621811/3a4e5e34-c51a-11e5-8660-4017f47bd38b.png)

(These are taken from an example study I set up on the staging site at: http://remit.staging.mysociety.org/studies/195)

We know that the timeline has some visual issues when studies have done lots of stages and we've ticketed that here: #39, but it should show the right information, even for withdrawn studies.

The timeline should show the following changes/events:
- When the study was created
- When the study's title changes
- When the study's stage changes
- When a document is added
- When a publication is added
- When an impact is added
- When a note is added
- When an enabler/barrier is added (currently you can only add these through the admin)

In particular, it's worth changing a study through all of the different stages so check that you're happy with the text it displays for each change.

Note: currently each event doesn't link anywhere like it could (e.g. to the relevant document or publication), we'll be working on that in the next sprint.

**Comment by kimmwest** [comment]
These look great - I'm really happy with how the text displays look.  not sure if you plan to colour code the 'dots' on the timeline but I guess that could be good if impact/disemmination/note/document were different colours.

I think we agreed in our meeting that 'output' was in fact something that the we added to the system and not a process stage so that does not need to be a progress category along the top bar 

We need the users of the system to be able to add enablers and barriers.  We also need them to add collaborators (by collaborators, I don't mean members of the study team, I mean e.g. ministry of health) - you should ahve seen that in the data schema?  I am open to how this happens but I think it makes sense to add similar buttons to 'add an impact' etc.

**Comment by kimmwest** [comment]
Also, it is a little unclear to me where withdrawn studies go to?  Can you show me an example?  Ta!

**Comment by stevenday** [comment]
@kimmwest, thanks for the feedback. I've created a couple of new tickets: #98 and #100 to track removing output and dealing with adding collaborators.

> not sure if you plan to colour code the 'dots' on the timeline but I guess that could be good if impact/disemmination/note/document were different colours.

They should be colour-coded into good/bad/negative actions, where adding any kind of output, documents etc is good and thus gets a green icon. I've made a note to discuss whether this is enough or whether each document or output type needs its own colour instead.

Since this was just a temporary ticket, I'm going to close it now and we'll create a new one for the sprint 3 review of these features.
