### ISSUE TITLE
Figure out how people are going to add Enablers and Barriers to studies.

### ISSUE THREAD

**Issue by stevenday** [mysociety/remit#60]
These are a bit like impacts, but more of a reflection on how a study went.

**Comment by zarino** [comment]
Makes sense to record these in the same way as you add a publication or a document to the study.

If we add a button to `.study-main__actions`, however, we'll need to rejig the buttons so that they still fit at the tablet / narrow desktop width. Perhaps the Document and Note forms could be combined in the same way as the outputs form is currently, and the buttons could be reworded slightly? Like:

![screen shot 2016-01-28 at 12 55 18](https://cloud.githubusercontent.com/assets/739624/12644989/b97c64a4-c5be-11e5-9174-f61c3f494a78.png)

**Comment by stevenday** [comment]
Hmm, I'm not sure those are very logical groupings, especially since publication / impact is also hiding disseminations, which are quite different (though the previous "Output" combined the three things quite well).

What about moving the sidebar down a bit so they get the whole width to play in ?

**Comment by zarino** [comment]
> (though the previous "Output" combined the three things quite well).

Yeah, what I'm worried about is "Output" is just a word I came up with. From what I can tell, MSF don't ever group these things together (or, if they do, they haven't told us the word they use for them). So I'm a bit worried they won't know to look under "Output" when they want to add publications and other stuff.

There are lots of other ways we could sort out the styling and layout of these buttons. I'll just need to set aside time to try a few things out.

**Comment by stevenday** [comment]
We have some feedback about wording of this now from @kimmwest: https://github.com/mysociety/remit/issues/58#issuecomment-180458954 but I'll open a new ticket to deal with that for the next sprint. This is done and merged in e5dcb95
